enum SkillProp {
  csr
  esr
}

type LeaderboardEntry {
  rank: Int!
  xuid: String!
  gamertag: String!
  matchId: String!
  matchDate: String!
  csr: Float!
  esr: Float!
}

type LeaderboardBucket {
  skill: Int!
  count: Int!
}

type Leaderboard {
  count: Int!
  skillBuckets: [LeaderboardBucket!]!
  entries(page: Int = 1): [LeaderboardEntry!]!
  gamertagIndex(gamertag: String!): Int!
}

type Gamerpic {
  small: String!
  medium: String!
  large: String!
  xlarge: String!
}

type Player {
  xuid: String!
  gamertag: String!
  gamerpic: Gamerpic!
}

type Query {
  playlistIds: [String!]!
  leaderboard(playlistId: String!, skillProp: SkillProp!): Leaderboard
  player(xuidOrGamertag: String!): Player
}
