enum SkillProp {
  csr
  esr
}

type LeaderboardEntry {
  rank: Int!
  xuid: String!
  gamertag: String!
  matchId: String!
  matchDate: String!
  csr: Float!
  esr: Float!
}

type LeaderboardBucket {
  skill: Int!
  count: Int!
}

type Query {
  leaderboardPlaylists: [String!]!
  leaderboardPlaylistSkillBuckets(
    playlistId: String!
    skillProp: SkillProp!
  ): [LeaderboardBucket!]!
  leaderboardPlaylistCount(playlistId: String!): Int!
  leaderboardPlaylistEntries(
    playlistId: String!
    skillProp: SkillProp!
    page: Int = 1
  ): [LeaderboardEntry!]!
  leaderboardGamertagIndex(
    playlistId: String!
    xuid: String!
    skillProp: SkillProp!
  ): Int!
}
